### ISSUE TITLE
Aggiungere troncamento del messaggio

### ISSUE THREAD

**Issue by valeriogalano** [valeriogalano/pensieriincodice-news-to-mastodon#3]
A volte il commento al documento può far superare al messaggio la lunghezza massima supportata da Mastodon. Esempio: https://github.com/valeriogalano/pensieriincodice-news-to-mastodon/actions/runs/11572866738/job/32213753720#step:5:30

La lunghezza del messaggio dovrebbe essere verificata. Il commento, se necessario, andrebbe poi troncato per far rientrare il messaggio nella lunghezza massima.

**Comment by progressify** [comment]
avvisami se ci sono ancora noie con questa issue 
dovrebbe essere ok ma non si può mai sapere se non testiamo :P

**Comment by valeriogalano** [comment]
Grazie
